### ISSUE TITLE
almost but not quite working with world dataset

### ISSUE THREAD

**Issue by sobakasu** [grgcombs/iOS-Shapefile#2]
almost but not quite working with TM_WORLD_BORDERS-0.3 from http://thematicmapping.org/downloads/world_borders.php

**Comment by sobakasu** [comment]
![screen shot 2014-11-02 at 11 52 25 am](https://cloud.githubusercontent.com/assets/8692/4873920/c1004550-622e-11e4-8f11-b5317babf676.png)

**Comment by grgcombs** [comment]
I wonder if this is due to polygons with holes? You ever figure out what the issue was?

**Comment by sobakasu** [comment]
wow I can't remember what I was using this for, I don't think I found a fix

**Comment by grgcombs** [comment]
It looks like this could've been due to validation errors in the shape file -- When I use Qgis and run a validation check, it throws up hundreds of errors.  But when I split up the shape file into many, one for each country, then simplify the polygons, it seems to work ok.  Still not convinced it's not somehow my fault in processing the shape file or constructing the polygons, but it does raise some questions about "unclean" vectors.
